### ISSUE TITLE
CindyGL examples missing on cindyjs.org/examples/

### ISSUE THREAD

**Issue by kranich** [CindyJS/website#1]
The examples from [examples/cindygl/](https://github.com/CindyJS/CindyJS/tree/master/examples/cindygl) seem to be missing on [cindyjs.org/examples/](cindyjs.org/examples/).

**Comment by gagern** [comment]
The cindyjs.org site isn't built automatically yet. I intend to hook that up to Travis like I did the automatic deployment of the built JS files, but I'm not sure when I'll manage to do so.

**Comment by gagern** [comment]
The automatic link from GitHub via Travis to the cindyjs.org server is now in place. Since 4d35f21909be9cf266806df39f40926ddde833fc we have the CindyGL examples at http://cindyjs.org/examples/cindygl/.

@montaga does that mean that the redirect http://cindyjs.org/cindygl/ can be changed now to point at that?

The index creation doesn't handle directories yet, nor does it work recursively. So we get a gulp-created index for `examples` and a apache-generated one for its subdirectories. Might be worth fixing at some later point.

**Comment by montaga** [comment]
Yes,  http://cindyjs.org/cindygl/ now can be redirected to http://cindyjs.org/examples/cindygl/. Thanks!

**Comment by gagern** [comment]
Updated the redirect. Thanks!
